scp tc_prio.sh PC1:~ && ssh PC1 sudo bash tc_prio.sh &
scp tc_prio.sh PC2:~ && ssh PC2 sudo bash tc_prio.sh &
scp tc_prio.sh PC3:~ && ssh PC3 sudo bash tc_prio.sh &
scp tc_prio.sh PC4:~ && ssh PC4 sudo bash tc_prio.sh &
scp tc_prio.sh PC5:~ && ssh PC5 sudo bash tc_prio.sh &
scp tc_prio.sh PC6:~ && ssh PC6 sudo bash tc_prio.sh &
scp tc_prio.sh PC7:~ && ssh PC7 sudo bash tc_prio.sh &
scp tc_prio.sh PC8:~ && ssh PC8 sudo bash tc_prio.sh &
scp tc_prio.sh PC9:~ && ssh PC9 sudo bash tc_prio.sh &
scp tc_prio.sh PC10:~ && ssh PC10 sudo bash tc_prio.sh &
